disabled_rules:
  - trailing_whitespace # Allow trailing whitespace in documentation
  - line_length # Swift Testing syntax can be verbose
  - identifier_name # Allow short variable names common in mathematical contexts
  - large_tuple # Property-based testing often uses large tuples
  - generic_type_name # Allow underscores in generic type names
  - force_unwrapping # Allow force unwrapping in test code where appropriate
  - operator_usage_whitespace # Allow flexible operator spacing
  - opening_brace # Allow flexible brace spacing
  - trailing_newline # Allow files without trailing newlines
  - multiline_arguments # Allow flexible argument formatting
  - multiline_parameters # Allow flexible parameter formatting
  - function_body_length # Allow longer function bodies in tests
  - function_parameter_count # Allow more parameters in testing functions
  - type_body_length # Allow longer type bodies
  - file_length # Allow longer files for comprehensive tests
  - cyclomatic_complexity # Allow higher complexity in test code
  - comment_spacing # Allow flexible comment spacing
  - colon # Allow flexible colon spacing
  - comma # Allow flexible comma spacing
  - closure_spacing # Allow flexible closure spacing
  - vertical_whitespace # Allow multiple blank lines for organization
  - statement_position # Allow flexible else/catch positioning
  - switch_case_alignment # Allow flexible switch case alignment
  - trailing_semicolon # Allow trailing semicolons
  - private_over_fileprivate # Allow fileprivate when needed
  - syntactic_sugar # Allow explicit type declarations when clearer
  - redundant_optional_initialization # Allow explicit nil initialization
  - redundant_discardable_let # Allow let _ = pattern
  - orphaned_doc_comment # Allow orphaned documentation
  - todo # Allow TODO comments during development

opt_in_rules:
  - array_init
  - contains_over_filter_count
  - empty_count
  - first_where
  - last_where
  - redundant_nil_coalescing
  - sorted_first_last

included:
  - Sources
  - Tests

excluded:
  - .build
  - .swiftpm
  - docs

# Keep some basic rules but with relaxed settings
nesting:
  type_level:
    warning: 3
    error: 4

# Disable the problematic custom rule
# custom_rules:
#   no_print:
#     name: "No Print Statements"
#     regex: '(?<!\/\/.*|\/\*[\s\S]*?\*\/)print\('
#     message: "Use proper logging instead of print statements"
#     severity: warning
