name: Swift CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    name: Test Swift ${{ matrix.swift-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # Test on macOS with Swift 6.0 and 6.1 using SwiftyLab/setup-swift
        os: [macos-latest]
        swift-version: ['6.0', '6.1']

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Swift
      uses: SwiftyLab/setup-swift@latest
      with:
        swift-version: ${{ matrix.swift-version }}

    - name: Check Swift Installation
      run: swift --version

    - name: Cache Swift build
      uses: actions/cache@v4
      with:
        path: |
          .build
          ~/.cache/org.swift.swiftpm
        key: ${{ runner.os }}-swift-${{ matrix.swift-version }}-${{ hashFiles('Package.swift', 'Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-swift-${{ matrix.swift-version }}-

    - name: Build
      run: swift build

    - name: Run tests
      run: swift test --enable-code-coverage

    - name: Generate code coverage report (macOS only)
      if: runner.os == 'macOS' && matrix.swift-version == '6.0'
      run: |
        xcrun llvm-cov export -format="lcov" \
          .build/debug/SwiftQCPackageTests.xctest/Contents/MacOS/SwiftQCPackageTests \
          -instr-profile .build/debug/codecov/default.profdata > coverage.lcov 2>/dev/null || true

    - name: Upload coverage to Codecov (macOS only)
      if: runner.os == 'macOS' && matrix.swift-version == '6.0'
      uses: codecov/codecov-action@v4
      with:
        file: coverage.lcov
        fail_ci_if_error: false

  lint:
    name: SwiftLint
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: SwiftLint
      uses: norio-nomura/action-swiftlint@3.2.1
      with:
        args: --reporter github-actions-logging


