name: Swift CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    name: Test Swift ${{ matrix.swift-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # Use macOS latest which has Swift 6.1+ by default
        os: [macos-latest]
        swift-version: ['6.1']

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Use System Swift
      run: |
        echo "Using system Swift on macOS latest"
        which swift
        swift --version

    - name: Check Swift Installation
      run: swift --version

    - name: Build
      run: swift build -v

    - name: Run tests
      run: swift test -v --enable-code-coverage

    - name: Generate code coverage report (macOS only)
      if: runner.os == 'macOS' && matrix.swift-version == '6.0'
      run: |
        xcrun llvm-cov export -format="lcov" \
          .build/debug/SwiftQCPackageTests.xctest/Contents/MacOS/SwiftQCPackageTests \
          -instr-profile .build/debug/codecov/default.profdata > coverage.lcov

    - name: Upload coverage to Codecov (macOS only)
      if: runner.os == 'macOS' && matrix.swift-version == '6.0'
      uses: codecov/codecov-action@v4
      with:
        file: coverage.lcov
        fail_ci_if_error: false

  lint:
    name: SwiftLint
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: SwiftLint
      uses: norio-nomura/action-swiftlint@3.2.1
      with:
        args: --reporter github-actions-logging

  documentation:
    name: Documentation Build
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Check Swift Installation
      run: swift --version

    - name: Build Documentation
      run: |
        swift package --allow-writing-to-directory docs \
          generate-documentation --target SwiftQC \
          --disable-indexing \
          --transform-for-static-hosting \
          --hosting-base-path SwiftQC \
          --output-path docs

    - name: Upload Documentation
      if: github.ref == 'refs/heads/main'
      uses: actions/upload-pages-artifact@v3
      with:
        path: docs

  deploy-docs:
    name: Deploy Documentation
    if: github.ref == 'refs/heads/main'
    needs: documentation
    runs-on: macos-latest
    permissions:
      pages: write
      id-token: write
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
